app:
    resource: "@AppBundle/Controller/"
    type:     annotation
#    path: /{_locale}/
captcha_routing:
  resource: "@CaptchaBundle/Resources/config/routing.yml"

apiroute:
    type: rest
    resource: AppBundle\Controller\Api\ApiController
    prefix: /{_country}/{_locale}/api
enquiryandsuggestion:
    type: rest
    resource: AppBundle\Controller\Api\EnquiryAndSuggestionController
    prefix: /{_country}/{_locale}/api
