# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        memory: ~
        webservice:
            id: app.webservice_user_provider
    encoders:
        AppBundle\Security\User\WebserviceUser:
            algorithm: md5
            iterations: 0
            encode_as_base64: false
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        wuser_area:
            context: wuser_area
            anonymous: ~
            pattern: ^/
            simple_form:
              login_path: login
              check_path: login
              authenticator: app.webservice_authenticator
              provider: webservice

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
       - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/, roles: ROLE_ADMIN }