# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        memory: ~
#        webservice:
        iktuser_provider:
            id: app.iktissab_user_provider
        iktadmin_provider:
            id: app.iktissab_admin_provider
    encoders:
        AppBundle\Security\User\IktissabUser:
            algorithm: md5
            iterations: 0
            encode_as_base64: false
        AppBundle\Security\Admin\IktissabAdmin:
                    algorithm: md5
                    iterations: 0
                    encode_as_base64: false
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/(%app_countries%)/(%app_locales%)/api/
            stateless: true
            wsse: true

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
        iktuser_area:
            context: iktuser_area
            anonymous: ~
            pattern: ^/(%app_countries%)/(%app_locales%)/*
            simple_form:
              success_handler: app.ikt_success_handler
#              default_target_path: homepage
              always_use_default_target_path: true
              login_path: login
              check_path: login
              authenticator: app.iktissab_authenticator
              provider: iktuser_provider
            logout:
              path: account_logout
              success_handler: app.logout_handler
        iktadmin_area:
            context: iktadmin_area
            anonymous: ~
            pattern: ^/admin
            simple_form:
              success_handler: app.iktadmin_success_handler
#             default_target_path: homepage
              login_path: /admin/admin
              check_path: /admin/admin
              authenticator: app.iktissabadmin_authenticator
              provider: iktadmin_provider
            logout:
              path: admin_logout
              success_handler: app.logoutadmin_handler

    access_control:
       - { path: ^/(%app_countries%)/(%app_locales%)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/(%app_countries%)/(%app_locales%)/account/, roles: ROLE_IKTUSER }
       - { path: ^/(%app_countries%)/(%app_locales%)/api/, roles: ROLE_API  }
       - { path: ^/admin/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, roles: ROLE_IKTADMIN }


