# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.iktissab_user_provider:
        class: AppBundle\Security\User\IktissabUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.iktissab_admin_provider:
            class: AppBundle\Security\Admin\IktissabAdminProvider
            arguments: ["@doctrine.orm.entity_manager"]
    app.iktissab_authenticator:
        class: AppBundle\Security\IktissabAuthenticator
        arguments: ["@security.password_encoder"]
    app.iktissabadmin_authenticator:
            class: AppBundle\Security\IktissabAdminAuthenticator
            arguments: ["@security.password_encoder"]

    app.activity_log:
        class: AppBundle\Services\ActivityLogService
        arguments: ["@doctrine.orm.entity_manager","@service_container"]
    app.ikt_success_handler:
        class: AppBundle\Security\IktissabSuccessHandler
        arguments: ["@router", "@service_container"]
    app.iktadmin_success_handler:
            class: AppBundle\Security\IktissabAdminSuccessHandler
            arguments: ["@router", "@service_container"]
    app.logout_handler:
        class: AppBundle\Security\LogoutHandler
        arguments: ["@router", "@service_container","@session"]
    app.rest_client:
        class: AppBundle\Services\RestClientService
        arguments: ["@circle.restclient","@serializer.encoder.json"]
    app.userlang_extension:
        class: AppBundle\Twig\UserlangExtension
        public: false
        arguments: ['@service_container']
        tags:
            - {name: twig.extension}
    app.sms_service:
        class: AppBundle\Services\SmsService
        arguments: ['@app.rest_client',%sms_parameters%]
