# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.iktissab_user_provider:
        class: AppBundle\Security\User\IktissabUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.iktissab_authenticator:
        class: AppBundle\Security\IktissabAuthenticator
        arguments: ["@security.password_encoder"]
    app.login_login:
        class: AppBundle\Services\LoginLogService
        arguments: ["@doctrine.orm.entity_manager"]
