# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.webservice_user_provider:
        class: AppBundle\Security\User\WebserviceUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.webservice_authenticator:
        class: AppBundle\Security\WebserviceAuthenticator
        arguments: ["@security.password_encoder"]
