<?php

namespace AppBundle\Entity\Repository;

/**
 * CmsPagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsPagesRepository extends \Doctrine\ORM\EntityRepository
{
}
