<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * ContactUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnquiryAndSuggestionRepository extends EntityRepository
{
    /**
     * @param $date
     * @return array
     */
    public function findByUserIPAndCreated($date)
    {
        return $this->_em->createQueryBuilder()->select("e")
            ->from("AppBundle:EnquiryAndSuggestion", "e")
            ->where("e.user_ip=:userip")
            ->andWhere("e.created>:date")
            ->setParameter("userip", $_SERVER['REMOTE_ADDR'])
            ->setParameter("date", $date)
            ->getQuery()
            ->getResult();
    }
}
