<?php

namespace AppBundle\Entity\Repository;

/**
 * FaqsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqsRepository extends \Doctrine\ORM\EntityRepository
{
}
