<?php

namespace AppBundle\Entity\Repository;

/**
 * FormSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormSettingsRepository extends \Doctrine\ORM\EntityRepository
{
}
