<?php

namespace AppBundle\Entity\Repository;

/**
 * LoginLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoginLogRepository extends \Doctrine\ORM\EntityRepository
{
}
