<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\NotificationSubscriptionDevices;
use Doctrine\ORM\Query\Expr;

/**
 * NotificationSubscriptionDevicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationSubscriptionDevicesRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $iktCard
     * @return int
     */
    public function GetNextSerial($iktCard)
    {
        $max = $this->_em->createQueryBuilder()
            ->select("MAX(nsd.serial)")
            ->from("AppBundle:NotificationSubscriptionDevices", "nsd")
            ->where("nsd.iktCard = :iktCard")
            ->setParameter("iktCard", $iktCard)
            ->getQuery()
            ->getSingleScalarResult();

        if($max == null) $max = 0;
        $max++;
        return $max;

    }

    /**
     * @param $uid
     * @param $token
     * @return mixed|NotificationSubscriptionDevices
     */
    public function  GetDeviceByDeviceUIDAndToken($uid, $token){
        return $this->_em
            ->createQueryBuilder()
            ->select("d")
            ->from("AppBundle:NotificationSubscriptionDevices", 'd')
            ->where('d.deviceUID = :deviceUID')
            ->andWhere('d.deviceToken = :deviceToken')
            ->setParameter('deviceUID', $uid)
            ->setParameter('deviceToken', $token)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
