<?php

namespace AppBundle\Entity\Repository;

/**
 * ResourcesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourcesRepository extends \Doctrine\ORM\EntityRepository
{
}
