<?php

namespace AppBundle\Entity\Repository;
use AppBundle\Entity\User;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchUsers($ikt,$email)
    {
        $builder = $this->_em->createQueryBuilder()->select(array('u'))
            ->from('AppBundle:User', 'u')
            ->orderBy('u.regDate', 'desc');
        if ($ikt != '') $builder->andWhere('u.iktCardNo = :ikt')->setParameter('ikt', $ikt);
        if ($email != '') $builder->andWhere('u.email like  :email')->setParameter('email', '%'. $email. '%');
        return $builder
            ->getQuery()
            ->setHydrationMode(3);
    }

    /**
     * @param array $cards
     * @return array|null
     */
    public function GetUsersByCards($cards = []){
        if(empty($cards)) return null;

        return $this->_em->createQueryBuilder()
            ->select('u')
            ->from('AppBundle:User', 'u')
            ->where('u.iktCardNo IN(:cards)')
            ->setParameter('cards',  implode(',', $cards))
            ->getQuery()
            ->getResult(3);

    }

}
